language: node_js
node_js:
  - 17.3
  
jobs:
  include:
  - node: stable
    env: NODE_OPTIONS=--openssl-legacy-provider

cache: npm

install:
- npm install

script:
  - npm install --save-dev eth-gas-reporter
  - npm install --save-dev @codechecks/client
  - npm test
